Repository Kunstmaan/KunstmaanCookieBundle, pull requests merged in 2018-06, with the labels that each got.

#2 Removed unused form field "label" and added default label to legal optin pp
  src/Resources/skeleton/legal/Entity/PageParts/LegalOptInPagePart.php
  src/Resources/skeleton/legal/Form/PageParts/LegalOptInPagePartAdminType.php
Labels: bug

#5 [CookieBundle] add pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#4 [CookieBundle] Fix npm package vulnerabilities
  package-lock.json
Labels: frontend

#6 Add option to increase version number of cookie consent
  README.md
  src/Entity/CookieConfig.php
  src/EventSubscriber/CookieBarEventSubscriber.php
  src/Form/CookieConfigType.php
  src/Helper/LegalCookieHelper.php
  src/Repository/CookieConfigRepository.php
  src/Resources/translations/messages.en.yml
  src/Twig/CookieTwigExtension.php
Labels: enhancement
