Repository Kunstmaan/KunstmaanCookieBundle, pull requests merged in 2019-05, with the labels that each got.

#35 [CookieBundle] Fix symfony 4 incompatibilities
  src/Resources/skeleton/legal/Entity/Pages/LegalPage.php
  src/Resources/skeleton/legal/Resources/views/Pages/LegalPage/view.html.twig
Labels: bug

#33 fixed error on cookie config save
  src/Entity/CookieConfig.php
Labels: backend, bug

#31 fixed js packages
  bin/index.js
  package-lock.json
  package.json
  src/Resources/ui/js/index.js
Labels: bug, frontend
