Repository Kunstmaan/KunstmaanCookieBundle, pull requests merged in 2019-02, with the labels that each got.

#22 fix for issue Kunstmaan#21: Hardcoded img path in sass files
  src/Resources/ui/scss/components/_btn-toggle.scss
  src/Resources/ui/scss/config/_variables.scss
  src/Resources/views/Components/CloseCookieModalButton.html.twig
  src/Resources/views/Components/CloseDetailButton.html.twig
  src/Resources/views/Svg/CloseCookieModalButtonIcon.html.twig
  src/Resources/views/Svg/CloseDetailButtonIcon.html.twig
Labels: bug, frontend

#26 Refactored for sf4
  composer.json
  src/Command/GenerateLegalCommand.php
  src/Controller/LegalController.php
  src/Generator/LegalGenerator.php
  src/Resources/config/services.yml
  src/Resources/skeleton/legal/DataFixtures/ORM/LegalGenerator/DefaultFixtures.php
  src/Resources/skeleton/legal/Entity/PageParts/LegalCenteredIconPagePart.php
  src/Resources/skeleton/legal/Entity/PageParts/LegalCookiesPagePart.php
  src/Resources/skeleton/legal/Entity/PageParts/LegalIconTextPagePart.php
  src/Resources/skeleton/legal/Entity/PageParts/LegalOptInPagePart.php
  src/Resources/skeleton/legal/Entity/PageParts/LegalTipPagePart.php
  src/Resources/skeleton/legal/Entity/Pages/LegalPage.php
  src/Resources/skeleton/legal/Resources/config/pageparts/legal_header.yml
  src/Resources/skeleton/legal/Resources/config/pageparts/legal_main.yml
  src/Resources/skeleton/legal/Resources/config/pagetemplates/legalpage.yml
  src/Resources/skeleton/legal/Resources/views/Pages/LegalPage/_content.html.twig
  src/Resources/views/Components/TabBarContentPanel.html.twig
Labels: enhancement

#30 Improve scss image vars
  src/Resources/ui/scss/components/_to-top-button.scss
  src/Resources/ui/scss/config/_variables.scss
Labels: enhancement, frontend
